// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID   string  `json:"id"`
	Name string  `json:"name"`
	Bio  *string `json:"bio,omitempty"`
}

type EditAuthor struct {
	Name *string `json:"name,omitempty"`
	Bio  *string `json:"bio,omitempty"`
}

type NewAuthor struct {
	Name string  `json:"name"`
	Bio  *string `json:"bio,omitempty"`
}
